name: Build and push Docker Image

on:
  push:
    paths:
      - "./*"
      - ".github/workflows/docker-image.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: check repository
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: Sources
          push: true
          tags: bvdcode/peertube-runner-gpu:latest
          file: Dockerfile

      - name: login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/peertube-runner-gpu:latest
          file: Dockerfile
